### ISSUE TITLE
[MVP QA] Zoomable Image Viewer

### ISSUE THREAD

**Issue by jsimic** [OregonDigital/OD2#1386]
### Descriptive summary

Features needed: pan and zoom of large image served via tiles from the back end. Back end needs to have IIIF support, take our derivative images and serve up the image tiles our front end needs. Openseadragon JS provides the ability to zoom images. Universal viewer is built on openseadragon and already built in. The question of what to use is do we have the functionality we need out of the universal viewer or do we need lower level access and then we implement openseadragon directly

### Expected behavior

Confirm Universal Viewer can
- [x] Enter and exit full screen
- [x] Pan on an image
- [x] Zoom on an image
~~- [ ] Image can be reset~~
- [x] Pan on a pdf
- [x] Zoom on a pdf
- [x] Navigate through a multi page pdf
~~- [ ] Pdf can be reset~~

### Related work

#30, #73, #78, #554, #746, #905, #1385 #937

**Comment by CGillen** [comment]
Additional QA:
- [ ] Universal Viewer is laid out with expected widgets, headers, and sidebars
- [ ] Content in Universal Viewer is presented as expected by default and contains the other expected layout options (side-by-side, single-page scrolling, etc).

**Comment by kmthorn** [comment]
[Example: The Beaver 1945](https://staging.oregondigital.org/concern/documents/12579s71x?locale=en) and [Example: 198601987 OSU Basketball Media Guide](https://staging.oregondigital.org/concern/documents/fx71c840p?locale=en) Derivative image is not filling the UV frame completely. Both of these items have different object dimensions. Reference: #1425

Turn off the Navigator Enabled. Settings → Navigator Enabled. This is make the navigation box be turned off by default. A user will need to manually turn it on. Reference: #1424 

There is something odd going on with items opened in a full screen and then brought back to default view. The UV viewer gets cut off and users are not able to see the three different view buttons. Items are also cut off. This is challenging to replicate because it worked on some browsers and not others. And on some people's computers and not others when tested. Reference: #1423 

Reset button does not exist within Universal Viewer. Remove from the checklist.

- [OD2 example: President George Peavy and the OSC Administrative Council](https://staging.oregondigital.org/concern/images/df719m437?locale=en)

- [Wellcome Library example](https://wellcomelibrary.org/item/b20417081#?c=0&m=0&s=0&cv=2&z=0.3742%2C0.2272%2C0.5399%2C0.2732)

- [British Library example](http://access.bl.uk/item/viewer/ark:/81055/vdc_00000004216E#?c=0&m=0&s=0&cv=5&xywh=333%2C719%2C1249%2C672). 

[1986-1987 Oregon State University Basketball Media Guide
](https://staging.oregondigital.org/concern/documents/fx71c840p?locale=en) when navigating the item, pagination is not displaying when a user clicks the next or previous page button that is located at the top of UV. Page numbers are assigned to this item. When you toggle from Page to Images then the page numbers appear. Reference: #1426

**Comment by CGillen** [comment]
Fixed by #2326

**Comment by jsimic** [comment]
Can't QA until issues found in #1423 are addressed

**Comment by petersec** [comment]
Issues related to #1423 and #1424 - QA pass

Issues related to #1425 - QA fail.  Derivative images for [The Beaver 1945](https://staging.oregondigital.org/concern/documents/12579s71x?locale=en#content) and [OSU Basketball Media Guide, 1986-87](https://staging.oregondigital.org/concern/documents/fx71c840p#content) (as examples) are still not filling the UV frame completely. Thumbnails on the [search results page](https://staging.oregondigital.org/catalog?utf8=%E2%9C%93&search_field=all_fields&q%5B%5D=1986-1987+Oregon+State+University+Basketball+Media+Guide#content) for these items also appear smaller.
